name: brandium
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82993
title: Consultoria em desenvolvimento de marca.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#565656'
    - '#1e1e1e'
    - '#7c7c7c'
    - '#9c9c9c'
    - '#ededed'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
